Module Constantes

    ' Perfiles deben corresponder a los de la tabla ido_usuarios
    Public Const P_PROMOTORA = "PROM"
    Public Const P_PRODMANAGER = "PRMA"
    Public Const P_EJECUTIVO = "EJEC"
    Public Const P_VENDEDORA = "VEND"

    Public Const COMPANYNAME = "ANTALIS CHILE"

    Public Const MODULO_POTENCIAL_CLIENTE As String = "POTCLI"
    Public Const MODULO_CATASTRO_MAQUINAS As String = "CAT_MAQ"
    Public Const MODULO_SEGUIMIENTO_METAS As String = "SEGMET"


    Public Const MODULO_RESUMEN_FACTURACION_X_CLIENTE As String = "RESFACXCLI"
    Public Const MODULO_RESUMEN_ECATALOGO_CARTERA_VIRTUAL As String = "RESECACARVIR"
    Public Const MODULO_RESUMEN_VENTAS_ECATALOGO As String = "RESVTASECAT"
    Public Const MODULO_MATRIZ_ANALISIS_VTA_CLI As String = "MTRANVTACLI"
    Public Const MODULO_RANKING_MG_VTA_CLIENTE As String = "RKMGVTACLI"

    Public Const OPMENU_ANALISIS_VENTAS_X_CLIENTE As String = "MENU_AVXC"



    Public Const CTE_OBJ_USER_INFO As String = "USER_INFO"
    Public Const CTE_OBJ_PERMISOS_USUARIO As String = "CTE_OBJ_PERMISOS_USUARIO"
    Public Const CTE_OBJ_USER_INFO_PERFIL As String = "CTE_OBJ_USER_INFO_PERFIL"


    Public Const CTE_ANDES_USERNAME As String = "CTE_ANDES_USERNAME"

    Public Const CTE_ANDES_USUARIO_AUTENTICADO As String = "CTE_ANDES_USUARIO_AUTENTICADO"
    Public Const CTE_ANDES_CODIGO_AGENTE As String = "CTE_ANDES_CODIGO_AGENTE"
    Public Const CTE_ANDES_CODIGO_TIPO_AGENTE As String = "CTE_ANDES_CODIGO_TIPO_AGENTE"
    Public Const CTE_ANDES_CODIGO_CELULA As String = "CTE_ANDES_CODIGO_CELULA"
    Public Const CTE_ANDES_SUPER_AGENTE As String = "CTE_ANDES_SUPER_AGENTE"
    Public Const CTE_ANDES_INFO_USUARIO As String = "USER_INFO"
    Public Const CTE_ANDES_GRUPO_AGENTE As String = "CTE_ANDES_GRUPO_AGENTE"
    Public Const CTE_ANDES_FILIAL_ACTIVA As String = "CTE_ANDES_FILIAL_ACTIVA"



    Public Const CTE_ANDES_VAL_TIPO_AGENTE_EJECUTIVO_COMERCIAL As String = "EJECO"
    Public Const CTE_ANDES_VAL_TIPO_AGENTE_SALES_ADVISOR As String = "EJEVE"
    Public Const CTE_ANDES_VAL_TIPO_AGENTE_GERENCIA As String = "GERENCIA"

    Public Const CTE_ANDES_VAL_GRUPO_AGENTE_CELULA As String = "CELULA"
    Public Const CTE_ANDES_VAL_GRUPO_AGENTE_VENTAS As String = "VENTAS"
    Public Const CTE_ANDES_VAL_GRUPO_TELEMARKETING As String = "TELEMKTG"

End Module

