'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2494
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2494.
'
Namespace cl.gms.andes.ws
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="OrgSrvSoap", [Namespace]:="http://tempuri.org/wsAndes/OrgSrv")>  _
    Public Class OrgSrv
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("app.cl.gms.andes.ws.OrgSrv")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://ws.andes.gms.cl/OrgSrv.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/obtieneSucursales", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneSucursales(ByVal codigoFilial As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneSucursales", New Object() {codigoFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneSucursales(ByVal codigoFilial As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneSucursales", New Object() {codigoFilial}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneSucursales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/listaSociedades", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaSociedades() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaSociedades", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaSociedades(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaSociedades", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaSociedades(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/listaPromotoras", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaPromotoras(ByVal codigoSociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaPromotoras", New Object() {codigoSociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaPromotoras(ByVal codigoSociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaPromotoras", New Object() {codigoSociedad}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaPromotoras(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/listaVendedoras", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaVendedoras(ByVal codigoSociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaVendedoras", New Object() {codigoSociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaVendedoras(ByVal codigoSociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaVendedoras", New Object() {codigoSociedad}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaVendedoras(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/listaVendedorasVirtuales", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaVendedorasVirtuales(ByVal codigoSociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaVendedorasVirtuales", New Object() {codigoSociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaVendedorasVirtuales(ByVal codigoSociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaVendedorasVirtuales", New Object() {codigoSociedad}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaVendedorasVirtuales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/listaAgentesPorTipo", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaAgentesPorTipo(ByVal codigoSociedad As String, ByVal codigoTipo As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaAgentesPorTipo", New Object() {codigoSociedad, codigoTipo})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaAgentesPorTipo(ByVal codigoSociedad As String, ByVal codigoTipo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaAgentesPorTipo", New Object() {codigoSociedad, codigoTipo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaAgentesPorTipo(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/listaClientesPorAgente", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaClientesPorAgente(ByVal codigoSociedad As String, ByVal codigoTipoAgente As String, ByVal codigoAgente As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaClientesPorAgente", New Object() {codigoSociedad, codigoTipoAgente, codigoAgente})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaClientesPorAgente(ByVal codigoSociedad As String, ByVal codigoTipoAgente As String, ByVal codigoAgente As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaClientesPorAgente", New Object() {codigoSociedad, codigoTipoAgente, codigoAgente}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaClientesPorAgente(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/obtieneIntegrantesCelula", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneIntegrantesCelula(ByVal codigoSociedad As String, ByVal codigoCelula As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneIntegrantesCelula", New Object() {codigoSociedad, codigoCelula})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneIntegrantesCelula(ByVal codigoSociedad As String, ByVal codigoCelula As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneIntegrantesCelula", New Object() {codigoSociedad, codigoCelula}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneIntegrantesCelula(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/OrgSrv/obtieneEstructuraComercialUsuario", RequestNamespace:="http://tempuri.org/wsAndes/OrgSrv", ResponseNamespace:="http://tempuri.org/wsAndes/OrgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneEstructuraComercialUsuario(ByVal codigoSociedad As String, ByVal username As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneEstructuraComercialUsuario", New Object() {codigoSociedad, username})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneEstructuraComercialUsuario(ByVal codigoSociedad As String, ByVal username As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneEstructuraComercialUsuario", New Object() {codigoSociedad, username}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneEstructuraComercialUsuario(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
