'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2494
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2494.
'
Namespace cl.gms.andes.ws.catastroPlotters
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="catastroPlottersSrvSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class catastroPlottersSrv
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("app.cl.gms.andes.ws.catastroPlotters.catastroPlottersSrv")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://pruebas.ws.andes.gms.cl/catastroPlottersSrv.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dummy1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dummy1() As stRegistroPlotter
            Dim results() As Object = Me.Invoke("dummy1", New Object(-1) {})
            Return CType(results(0),stRegistroPlotter)
        End Function
        
        '<remarks/>
        Public Function Begindummy1(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dummy1", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Enddummy1(ByVal asyncResult As System.IAsyncResult) As stRegistroPlotter
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stRegistroPlotter)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneRegistroPlottersClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneRegistroPlottersClientes(ByVal codigoSociedad As String, ByVal codigoCliente As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneRegistroPlottersClientes", New Object() {codigoSociedad, codigoCliente, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneRegistroPlottersClientes(ByVal codigoSociedad As String, ByVal codigoCliente As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneRegistroPlottersClientes", New Object() {codigoSociedad, codigoCliente, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneRegistroPlottersClientes(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtienePlotters", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtienePlotters(ByVal codigoSociedad As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtienePlotters", New Object() {codigoSociedad, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtienePlotters(ByVal codigoSociedad As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtienePlotters", New Object() {codigoSociedad, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtienePlotters(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneTiposTintas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneTiposTintas(ByVal codigoSociedad As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneTiposTintas", New Object() {codigoSociedad, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneTiposTintas(ByVal codigoSociedad As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneTiposTintas", New Object() {codigoSociedad, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneTiposTintas(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresaNuevoRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ingresaNuevoRegistroMaquinaCliente(ByVal codigoSociedad As String, ByVal codigoCliente As String, ByVal idPlotter As Integer, ByVal cantidad As Integer, ByVal idTipoTinta As Integer, ByVal observaciones As String, ByRef msgError As String) As Integer
            Dim results() As Object = Me.Invoke("ingresaNuevoRegistroMaquinaCliente", New Object() {codigoSociedad, codigoCliente, idPlotter, cantidad, idTipoTinta, observaciones, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginingresaNuevoRegistroMaquinaCliente(ByVal codigoSociedad As String, ByVal codigoCliente As String, ByVal idPlotter As Integer, ByVal cantidad As Integer, ByVal idTipoTinta As Integer, ByVal observaciones As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ingresaNuevoRegistroMaquinaCliente", New Object() {codigoSociedad, codigoCliente, idPlotter, cantidad, idTipoTinta, observaciones, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndingresaNuevoRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizaRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function actualizaRegistroMaquinaCliente(ByVal idRegistro As Integer, ByVal codigoSociedad As String, ByVal codigoCliente As String, ByVal idPlotter As Integer, ByVal cantidad As Integer, ByVal idTipoTinta As Integer, ByVal observaciones As String, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.Invoke("actualizaRegistroMaquinaCliente", New Object() {idRegistro, codigoSociedad, codigoCliente, idPlotter, cantidad, idTipoTinta, observaciones, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginactualizaRegistroMaquinaCliente(ByVal idRegistro As Integer, ByVal codigoSociedad As String, ByVal codigoCliente As String, ByVal idPlotter As Integer, ByVal cantidad As Integer, ByVal idTipoTinta As Integer, ByVal observaciones As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("actualizaRegistroMaquinaCliente", New Object() {idRegistro, codigoSociedad, codigoCliente, idPlotter, cantidad, idTipoTinta, observaciones, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndactualizaRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminaRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function eliminaRegistroMaquinaCliente(ByVal idRegistro As Integer, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.Invoke("eliminaRegistroMaquinaCliente", New Object() {idRegistro, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BegineliminaRegistroMaquinaCliente(ByVal idRegistro As Integer, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("eliminaRegistroMaquinaCliente", New Object() {idRegistro, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndeliminaRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneRegistroMaquinaCliente(ByVal idRegistro As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneRegistroMaquinaCliente", New Object() {idRegistro, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneRegistroMaquinaCliente(ByVal idRegistro As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneRegistroMaquinaCliente", New Object() {idRegistro, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class stRegistroPlotter
        
        '<remarks/>
        Public idRegistro As Integer
        
        '<remarks/>
        Public codigoCliente As String
        
        '<remarks/>
        Public idPlotter As Integer
        
        '<remarks/>
        Public dmcPlotter As String
        
        '<remarks/>
        Public cantidad As Integer
        
        '<remarks/>
        Public idTipoTinta As Integer
    End Class
End Namespace
