'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2494
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2494.
'
Namespace cl.gms.andes.ws.clientes
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="clientesSrvSoap", [Namespace]:="http://tempuri.org/wsAndes/Service1")>  _
    Public Class clientesSrv
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("app.cl.gms.andes.ws.clientes.clientesSrv")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://ws.andes.gms.cl/clientessrv.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/Service1/obtieneMaestroCliente", RequestNamespace:="http://tempuri.org/wsAndes/Service1", ResponseNamespace:="http://tempuri.org/wsAndes/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneMaestroCliente(ByVal codigoFilial As String, ByVal codigoCliente As String, ByVal buscaEnMailing As Boolean) As stCliente
            Dim results() As Object = Me.Invoke("obtieneMaestroCliente", New Object() {codigoFilial, codigoCliente, buscaEnMailing})
            Return CType(results(0),stCliente)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneMaestroCliente(ByVal codigoFilial As String, ByVal codigoCliente As String, ByVal buscaEnMailing As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneMaestroCliente", New Object() {codigoFilial, codigoCliente, buscaEnMailing}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneMaestroCliente(ByVal asyncResult As System.IAsyncResult) As stCliente
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stCliente)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/Service1/listaClientesCarteraPromotora", RequestNamespace:="http://tempuri.org/wsAndes/Service1", ResponseNamespace:="http://tempuri.org/wsAndes/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaClientesCarteraPromotora(ByVal codigoFilial As String, ByVal codigoPromotora As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaClientesCarteraPromotora", New Object() {codigoFilial, codigoPromotora})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaClientesCarteraPromotora(ByVal codigoFilial As String, ByVal codigoPromotora As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaClientesCarteraPromotora", New Object() {codigoFilial, codigoPromotora}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaClientesCarteraPromotora(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/Service1/listaClientesCarteraVirtual", RequestNamespace:="http://tempuri.org/wsAndes/Service1", ResponseNamespace:="http://tempuri.org/wsAndes/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaClientesCarteraVirtual(ByVal codigoSociedad As String, ByVal codigoVendedora As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaClientesCarteraVirtual", New Object() {codigoSociedad, codigoVendedora})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaClientesCarteraVirtual(ByVal codigoSociedad As String, ByVal codigoVendedora As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaClientesCarteraVirtual", New Object() {codigoSociedad, codigoVendedora}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaClientesCarteraVirtual(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/Service1/obtieneClientes", RequestNamespace:="http://tempuri.org/wsAndes/Service1", ResponseNamespace:="http://tempuri.org/wsAndes/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneClientes(ByVal codigoFilial As String, ByVal codigoAgente As String, ByVal codigoCliente As String, ByVal razonSocial As String, ByVal buscaEnMailing As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneClientes", New Object() {codigoFilial, codigoAgente, codigoCliente, razonSocial, buscaEnMailing})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneClientes(ByVal codigoFilial As String, ByVal codigoAgente As String, ByVal codigoCliente As String, ByVal razonSocial As String, ByVal buscaEnMailing As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneClientes", New Object() {codigoFilial, codigoAgente, codigoCliente, razonSocial, buscaEnMailing}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneClientes(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsAndes/Service1")>  _
    Public Class stCliente
        
        '<remarks/>
        Public codigoFilial As String
        
        '<remarks/>
        Public codigoCliente As String
        
        '<remarks/>
        Public nombre As String
        
        '<remarks/>
        Public codigoPromotora As String
        
        '<remarks/>
        Public nombrePromotora As String
        
        '<remarks/>
        Public codigoCobrador As String
        
        '<remarks/>
        Public nombreCobrador As String
        
        '<remarks/>
        Public codigoFormaPago As String
        
        '<remarks/>
        Public codigoPlazoPago As String
        
        '<remarks/>
        Public valTopeCredito As Double
        
        '<remarks/>
        Public indicadorActivo As Boolean
        
        '<remarks/>
        Public valDeuda As Double
        
        '<remarks/>
        Public valPPPA As Double
        
        '<remarks/>
        Public direccion As Object
        
        '<remarks/>
        Public codigoComuna As Object
        
        '<remarks/>
        Public nombreComuna As Object
        
        '<remarks/>
        Public codigoCiudad As Object
        
        '<remarks/>
        Public nombreCiudad As Object
        
        '<remarks/>
        Public telefono As Object
        
        '<remarks/>
        Public fax As Object
        
        '<remarks/>
        Public movil As Object
        
        '<remarks/>
        Public rutCliente As Object
        
        '<remarks/>
        Public codigoPais As Object
        
        '<remarks/>
        Public nombrePais As Object
        
        '<remarks/>
        Public codigoRegion As Object
        
        '<remarks/>
        Public nombreRegion As Object
    End Class
End Namespace
