'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2494
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2494.
'
Namespace cl.gms.andes.ws.materiales
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="materialesSrvSoap", [Namespace]:="http://tempuri.org/wsAndes/materialesSrv")>  _
    Public Class materialesSrv
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("app.cl.gms.andes.ws.materiales.materialesSrv")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://ws.andes.gms.cl/materialesSrv.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneAreas", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneAreas(ByVal codigoFilial As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneAreas", New Object() {codigoFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneAreas(ByVal codigoFilial As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneAreas", New Object() {codigoFilial}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneAreas(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneFamilias", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneFamilias(ByVal codigoFilial As String, ByVal codigoArea As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneFamilias", New Object() {codigoFilial, codigoArea})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneFamilias(ByVal codigoFilial As String, ByVal codigoArea As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneFamilias", New Object() {codigoFilial, codigoArea}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneFamilias(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneSubFamilias", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneSubFamilias(ByVal codigoFilial As String, ByVal codigoArea As String, ByVal codigoFamilia As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneSubFamilias", New Object() {codigoFilial, codigoArea, codigoFamilia})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneSubFamilias(ByVal codigoFilial As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneSubFamilias", New Object() {codigoFilial, codigoArea, codigoFamilia}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneSubFamilias(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneMateriales", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneMateriales(ByVal codigoFilial As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneMateriales", New Object() {codigoFilial, codigoArea, codigoFamilia, codigoSubfamilia})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneMateriales(ByVal codigoFilial As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneMateriales", New Object() {codigoFilial, codigoArea, codigoFamilia, codigoSubfamilia}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneMateriales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneMaterial", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneMaterial(ByVal codigoFilial As String, ByVal codigoProducto As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneMaterial", New Object() {codigoFilial, codigoProducto})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneMaterial(ByVal codigoFilial As String, ByVal codigoProducto As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneMaterial", New Object() {codigoFilial, codigoProducto}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneMaterial(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneInfoJerarquiaMaterial", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneInfoJerarquiaMaterial(ByVal codigoSubfamilia As String) As stJerarquiaMaterial
            Dim results() As Object = Me.Invoke("obtieneInfoJerarquiaMaterial", New Object() {codigoSubfamilia})
            Return CType(results(0),stJerarquiaMaterial)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneInfoJerarquiaMaterial(ByVal codigoSubfamilia As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneInfoJerarquiaMaterial", New Object() {codigoSubfamilia}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneInfoJerarquiaMaterial(ByVal asyncResult As System.IAsyncResult) As stJerarquiaMaterial
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stJerarquiaMaterial)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneEncargadosSubfamilias", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneEncargadosSubfamilias(ByVal codigoFilial As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneEncargadosSubfamilias", New Object() {codigoFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneEncargadosSubfamilias(ByVal codigoFilial As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneEncargadosSubfamilias", New Object() {codigoFilial}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneEncargadosSubfamilias(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneProveedores", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneProveedores(ByVal codigoSociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneProveedores", New Object() {codigoSociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneProveedores(ByVal codigoSociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneProveedores", New Object() {codigoSociedad}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneProveedores(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneProveedoresPorJerarquia", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneProveedoresPorJerarquia(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneProveedoresPorJerarquia", New Object() {codigoSociedad, codigoArea, codigoFamilia, codigoSubfamilia})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneProveedoresPorJerarquia(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneProveedoresPorJerarquia", New Object() {codigoSociedad, codigoArea, codigoFamilia, codigoSubfamilia}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneProveedoresPorJerarquia(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneMaterialesPorJerarquiaProveedor", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneMaterialesPorJerarquiaProveedor(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String, ByVal codigoProveedor As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneMaterialesPorJerarquiaProveedor", New Object() {codigoSociedad, codigoArea, codigoFamilia, codigoSubfamilia, codigoProveedor})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneMaterialesPorJerarquiaProveedor(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String, ByVal codigoProveedor As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneMaterialesPorJerarquiaProveedor", New Object() {codigoSociedad, codigoArea, codigoFamilia, codigoSubfamilia, codigoProveedor}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneMaterialesPorJerarquiaProveedor(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneMaterialesPorProveedor", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneMaterialesPorProveedor(ByVal codigoSociedad As String, ByVal codigoProveedor As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneMaterialesPorProveedor", New Object() {codigoSociedad, codigoProveedor})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneMaterialesPorProveedor(ByVal codigoSociedad As String, ByVal codigoProveedor As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneMaterialesPorProveedor", New Object() {codigoSociedad, codigoProveedor}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneMaterialesPorProveedor(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneAreasProdManager", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneAreasProdManager(ByVal codigoSociedad As String, ByVal prodManager As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneAreasProdManager", New Object() {codigoSociedad, prodManager})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneAreasProdManager(ByVal codigoSociedad As String, ByVal prodManager As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneAreasProdManager", New Object() {codigoSociedad, prodManager}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneAreasProdManager(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneFamiliasProdManager", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneFamiliasProdManager(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal prodManager As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneFamiliasProdManager", New Object() {codigoSociedad, codigoArea, prodManager})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneFamiliasProdManager(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal prodManager As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneFamiliasProdManager", New Object() {codigoSociedad, codigoArea, prodManager}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneFamiliasProdManager(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAndes/materialesSrv/obtieneSubFamiliasProdManager", RequestNamespace:="http://tempuri.org/wsAndes/materialesSrv", ResponseNamespace:="http://tempuri.org/wsAndes/materialesSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneSubFamiliasProdManager(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal prodManager As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneSubFamiliasProdManager", New Object() {codigoSociedad, codigoArea, codigoFamilia, prodManager})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneSubFamiliasProdManager(ByVal codigoSociedad As String, ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal prodManager As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneSubFamiliasProdManager", New Object() {codigoSociedad, codigoArea, codigoFamilia, prodManager}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneSubFamiliasProdManager(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsAndes/materialesSrv")>  _
    Public Class stJerarquiaMaterial
        
        '<remarks/>
        Public area As stArea
        
        '<remarks/>
        Public familia As stFamilia
        
        '<remarks/>
        Public subfamilia As stSubfamilia
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsAndes/materialesSrv")>  _
    Public Class stArea
        
        '<remarks/>
        Public codigo As String
        
        '<remarks/>
        Public denominacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsAndes/materialesSrv")>  _
    Public Class stSubfamilia
        
        '<remarks/>
        Public codigo As String
        
        '<remarks/>
        Public denominacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsAndes/materialesSrv")>  _
    Public Class stFamilia
        
        '<remarks/>
        Public codigo As String
        
        '<remarks/>
        Public denominacion As String
    End Class
End Namespace
