'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2494
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2494.
'
Namespace cl.gms.aton
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="orgSrvSoap", [Namespace]:="http://tempuri.org/aton/orgSrv")>  _
    Public Class orgSrv
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("app.cl.gms.aton.orgSrv")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://aton.gms.cl/OrgSrv.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/aton/orgSrv/listaDepartamentos", RequestNamespace:="http://tempuri.org/aton/orgSrv", ResponseNamespace:="http://tempuri.org/aton/orgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaDepartamentos(ByVal codigoFilial As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaDepartamentos", New Object() {codigoFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaDepartamentos(ByVal codigoFilial As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaDepartamentos", New Object() {codigoFilial}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaDepartamentos(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/aton/orgSrv/listaFiliales", RequestNamespace:="http://tempuri.org/aton/orgSrv", ResponseNamespace:="http://tempuri.org/aton/orgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaFiliales() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaFiliales", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaFiliales(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaFiliales", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaFiliales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/aton/orgSrv/listaSucursales", RequestNamespace:="http://tempuri.org/aton/orgSrv", ResponseNamespace:="http://tempuri.org/aton/orgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaSucursales(ByVal codigoFilial As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaSucursales", New Object() {codigoFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaSucursales(ByVal codigoFilial As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaSucursales", New Object() {codigoFilial}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaSucursales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/aton/orgSrv/listaSociedades", RequestNamespace:="http://tempuri.org/aton/orgSrv", ResponseNamespace:="http://tempuri.org/aton/orgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaSociedades() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaSociedades", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaSociedades(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaSociedades", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaSociedades(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/aton/orgSrv/listaPromotoras", RequestNamespace:="http://tempuri.org/aton/orgSrv", ResponseNamespace:="http://tempuri.org/aton/orgSrv", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaPromotoras(ByVal codigoSociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("listaPromotoras", New Object() {codigoSociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginlistaPromotoras(ByVal codigoSociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaPromotoras", New Object() {codigoSociedad}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaPromotoras(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
