'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2443
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2443.
'
Namespace ecatsrv
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="eCatSrvSoap", [Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class eCatSrv
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("app.ecatsrv.eCatSrv")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/ws/ecatsrv.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getAreas", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getAreas() As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stAreas()
            Dim results() As Object = Me.Invoke("getAreas", New Object(-1) {})
            Return CType(results(0),stAreas())
        End Function
        
        '<remarks/>
        Public Function BegingetAreas(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getAreas", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetAreas(ByVal asyncResult As System.IAsyncResult) As stAreas()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stAreas())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getFamilias", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getFamilias(ByVal codigoArea As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stFamilias()
            Dim results() As Object = Me.Invoke("getFamilias", New Object() {codigoArea})
            Return CType(results(0),stFamilias())
        End Function
        
        '<remarks/>
        Public Function BegingetFamilias(ByVal codigoArea As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getFamilias", New Object() {codigoArea}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetFamilias(ByVal asyncResult As System.IAsyncResult) As stFamilias()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stFamilias())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getSubFamilias", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getSubFamilias(ByVal codigoArea As String, ByVal codigoFamilia As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stSubFamilias()
            Dim results() As Object = Me.Invoke("getSubFamilias", New Object() {codigoArea, codigoFamilia})
            Return CType(results(0),stSubFamilias())
        End Function
        
        '<remarks/>
        Public Function BegingetSubFamilias(ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getSubFamilias", New Object() {codigoArea, codigoFamilia}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetSubFamilias(ByVal asyncResult As System.IAsyncResult) As stSubFamilias()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stSubFamilias())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getAtributos", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getAtributos(ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stAtributos()
            Dim results() As Object = Me.Invoke("getAtributos", New Object() {codigoArea, codigoFamilia, codigoSubfamilia})
            Return CType(results(0),stAtributos())
        End Function
        
        '<remarks/>
        Public Function BegingetAtributos(ByVal codigoArea As String, ByVal codigoFamilia As String, ByVal codigoSubfamilia As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getAtributos", New Object() {codigoArea, codigoFamilia, codigoSubfamilia}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetAtributos(ByVal asyncResult As System.IAsyncResult) As stAtributos()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stAtributos())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getAtributosXProd", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getAtributosXProd(ByVal codigoProducto As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stAtribXProd()
            Dim results() As Object = Me.Invoke("getAtributosXProd", New Object() {codigoProducto})
            Return CType(results(0),stAtribXProd())
        End Function
        
        '<remarks/>
        Public Function BegingetAtributosXProd(ByVal codigoProducto As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getAtributosXProd", New Object() {codigoProducto}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetAtributosXProd(ByVal asyncResult As System.IAsyncResult) As stAtribXProd()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stAtribXProd())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getValoresAtributos", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getValoresAtributos( _
                    ByVal codigoArea As String,  _
                    ByVal codigoFamilia As String,  _
                    ByVal codigoSubfamilia As String,  _
                    ByVal codigoAtributo As String,  _
                    ByVal codigoAtributo1 As String,  _
                    ByVal codigoValorAtributo1 As String,  _
                    ByVal codigoAtributo2 As String,  _
                    ByVal codigoValorAtributo2 As String,  _
                    ByVal codigoAtributo3 As String,  _
                    ByVal codigoValorAtributo3 As String,  _
                    ByVal codigoAtributo4 As String,  _
                    ByVal codigoValorAtributo4 As String,  _
                    ByVal codigoAtributo5 As String,  _
                    ByVal codigoValorAtributo5 As String,  _
                    ByVal codigoAtributo6 As String,  _
                    ByVal codigoValorAtributo6 As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stValoresAtributos()
            Dim results() As Object = Me.Invoke("getValoresAtributos", New Object() {codigoArea, codigoFamilia, codigoSubfamilia, codigoAtributo, codigoAtributo1, codigoValorAtributo1, codigoAtributo2, codigoValorAtributo2, codigoAtributo3, codigoValorAtributo3, codigoAtributo4, codigoValorAtributo4, codigoAtributo5, codigoValorAtributo5, codigoAtributo6, codigoValorAtributo6})
            Return CType(results(0),stValoresAtributos())
        End Function
        
        '<remarks/>
        Public Function BegingetValoresAtributos( _
                    ByVal codigoArea As String,  _
                    ByVal codigoFamilia As String,  _
                    ByVal codigoSubfamilia As String,  _
                    ByVal codigoAtributo As String,  _
                    ByVal codigoAtributo1 As String,  _
                    ByVal codigoValorAtributo1 As String,  _
                    ByVal codigoAtributo2 As String,  _
                    ByVal codigoValorAtributo2 As String,  _
                    ByVal codigoAtributo3 As String,  _
                    ByVal codigoValorAtributo3 As String,  _
                    ByVal codigoAtributo4 As String,  _
                    ByVal codigoValorAtributo4 As String,  _
                    ByVal codigoAtributo5 As String,  _
                    ByVal codigoValorAtributo5 As String,  _
                    ByVal codigoAtributo6 As String,  _
                    ByVal codigoValorAtributo6 As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getValoresAtributos", New Object() {codigoArea, codigoFamilia, codigoSubfamilia, codigoAtributo, codigoAtributo1, codigoValorAtributo1, codigoAtributo2, codigoValorAtributo2, codigoAtributo3, codigoValorAtributo3, codigoAtributo4, codigoValorAtributo4, codigoAtributo5, codigoValorAtributo5, codigoAtributo6, codigoValorAtributo6}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetValoresAtributos(ByVal asyncResult As System.IAsyncResult) As stValoresAtributos()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stValoresAtributos())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getProductos", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProductos( _
                    ByVal codigoArea As String,  _
                    ByVal codigoFamilia As String,  _
                    ByVal codigoSubfamilia As String,  _
                    ByVal codigoProducto As String,  _
                    ByVal codigoAtributo1 As String,  _
                    ByVal codigoValorAtributo1 As String,  _
                    ByVal codigoAtributo2 As String,  _
                    ByVal codigoValorAtributo2 As String,  _
                    ByVal codigoAtributo3 As String,  _
                    ByVal codigoValorAtributo3 As String,  _
                    ByVal codigoAtributo4 As String,  _
                    ByVal codigoValorAtributo4 As String,  _
                    ByVal codigoAtributo5 As String,  _
                    ByVal codigoValorAtributo5 As String,  _
                    ByVal codigoAtributo6 As String,  _
                    ByVal codigoValorAtributo6 As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stProductos()
            Dim results() As Object = Me.Invoke("getProductos", New Object() {codigoArea, codigoFamilia, codigoSubfamilia, codigoProducto, codigoAtributo1, codigoValorAtributo1, codigoAtributo2, codigoValorAtributo2, codigoAtributo3, codigoValorAtributo3, codigoAtributo4, codigoValorAtributo4, codigoAtributo5, codigoValorAtributo5, codigoAtributo6, codigoValorAtributo6})
            Return CType(results(0),stProductos())
        End Function
        
        '<remarks/>
        Public Function BegingetProductos( _
                    ByVal codigoArea As String,  _
                    ByVal codigoFamilia As String,  _
                    ByVal codigoSubfamilia As String,  _
                    ByVal codigoProducto As String,  _
                    ByVal codigoAtributo1 As String,  _
                    ByVal codigoValorAtributo1 As String,  _
                    ByVal codigoAtributo2 As String,  _
                    ByVal codigoValorAtributo2 As String,  _
                    ByVal codigoAtributo3 As String,  _
                    ByVal codigoValorAtributo3 As String,  _
                    ByVal codigoAtributo4 As String,  _
                    ByVal codigoValorAtributo4 As String,  _
                    ByVal codigoAtributo5 As String,  _
                    ByVal codigoValorAtributo5 As String,  _
                    ByVal codigoAtributo6 As String,  _
                    ByVal codigoValorAtributo6 As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getProductos", New Object() {codigoArea, codigoFamilia, codigoSubfamilia, codigoProducto, codigoAtributo1, codigoValorAtributo1, codigoAtributo2, codigoValorAtributo2, codigoAtributo3, codigoValorAtributo3, codigoAtributo4, codigoValorAtributo4, codigoAtributo5, codigoValorAtributo5, codigoAtributo6, codigoValorAtributo6}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetProductos(ByVal asyncResult As System.IAsyncResult) As stProductos()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stProductos())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/resuelveCotizacion", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function resuelveCotizacion(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("resuelveCotizacion", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginresuelveCotizacion(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("resuelveCotizacion", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndresuelveCotizacion(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/ingresaPedido", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ingresaPedido(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("ingresaPedido", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginingresaPedido(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ingresaPedido", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndingresaPedido(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/consultaPrecios", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaPrecios(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("consultaPrecios", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginconsultaPrecios(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultaPrecios", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultaPrecios(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/listaDetallePedido", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaDetallePedido(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("listaDetallePedido", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginlistaDetallePedido(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaDetallePedido", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaDetallePedido(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/listaPedidos", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listaPedidos(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("listaPedidos", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginlistaPedidos(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listaPedidos", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistaPedidos(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/obtieneDetalleCliente", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneDetalleCliente(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("obtieneDetalleCliente", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneDetalleCliente(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneDetalleCliente", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneDetalleCliente(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/obtieneStockMaterial", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneStockMaterial(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("obtieneStockMaterial", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneStockMaterial(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneStockMaterial", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneStockMaterial(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/obtieneParametrosSap", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneParametrosSap(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("obtieneParametrosSap", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneParametrosSap(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneParametrosSap", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneParametrosSap(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/rep_zsd53", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function rep_zsd53(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("rep_zsd53", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function Beginrep_zsd53(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("rep_zsd53", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endrep_zsd53(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/obtieneEstadoPedido", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneEstadoPedido(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("obtieneEstadoPedido", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneEstadoPedido(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneEstadoPedido", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneEstadoPedido(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/obtieneEstadoReparto", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneEstadoReparto(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("obtieneEstadoReparto", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneEstadoReparto(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneEstadoReparto", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneEstadoReparto(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/obtieneDetalleEntrega", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneDetalleEntrega(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("obtieneDetalleEntrega", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneDetalleEntrega(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneDetalleEntrega", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneDetalleEntrega(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getProductosXDescripcion", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProductosXDescripcion(ByVal patron As String) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stProductos()
            Dim results() As Object = Me.Invoke("getProductosXDescripcion", New Object() {patron})
            Return CType(results(0),stProductos())
        End Function
        
        '<remarks/>
        Public Function BegingetProductosXDescripcion(ByVal patron As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getProductosXDescripcion", New Object() {patron}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetProductosXDescripcion(ByVal asyncResult As System.IAsyncResult) As stProductos()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stProductos())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getProductosXHistoria", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProductosXHistoria(ByVal codigoCliente As String, ByVal fechaIni As Date, ByVal fechaFin As Date) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> stProductos()
            Dim results() As Object = Me.Invoke("getProductosXHistoria", New Object() {codigoCliente, fechaIni, fechaFin})
            Return CType(results(0),stProductos())
        End Function
        
        '<remarks/>
        Public Function BegingetProductosXHistoria(ByVal codigoCliente As String, ByVal fechaIni As Date, ByVal fechaFin As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getProductosXHistoria", New Object() {codigoCliente, fechaIni, fechaFin}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetProductosXHistoria(ByVal asyncResult As System.IAsyncResult) As stProductos()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stProductos())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getUsuario", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getUsuario(ByVal codigoFilial As String, ByVal codigoSucursal As String, ByVal codigoCliente As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getUsuario", New Object() {codigoFilial, codigoSucursal, codigoCliente})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BegingetUsuario(ByVal codigoFilial As String, ByVal codigoSucursal As String, ByVal codigoCliente As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getUsuario", New Object() {codigoFilial, codigoSucursal, codigoCliente}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetUsuario(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getPrivilegio", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getPrivilegio(ByVal codigoFilial As String, ByVal codigoSucursal As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getPrivilegio", New Object() {codigoFilial, codigoSucursal})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BegingetPrivilegio(ByVal codigoFilial As String, ByVal codigoSucursal As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getPrivilegio", New Object() {codigoFilial, codigoSucursal}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetPrivilegio(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/getDocumento", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDocumento(ByVal codigoFilial As String, ByVal codigoSucursal As String, ByVal codigoCliente As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getDocumento", New Object() {codigoFilial, codigoSucursal, codigoCliente})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BegingetDocumento(ByVal codigoFilial As String, ByVal codigoSucursal As String, ByVal codigoCliente As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getDocumento", New Object() {codigoFilial, codigoSucursal, codigoCliente}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetDocumento(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/obtieneStockMaterial2", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneStockMaterial2(ByVal xmlMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("obtieneStockMaterial2", New Object() {xmlMsg})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneStockMaterial2(ByVal xmlMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneStockMaterial2", New Object() {xmlMsg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneStockMaterial2(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ecatSrv/Service1/testCola", RequestNamespace:="http://tempuri.org/ecatSrv/Service1", ResponseNamespace:="http://tempuri.org/ecatSrv/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function testCola() As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("testCola", New Object(-1) {})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BegintestCola(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("testCola", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndtestCola(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class stAreas
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public msgError As String
        
        '<remarks/>
        Public cod_area As String
        
        '<remarks/>
        Public gls_area As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class stProductos
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public msgError As String
        
        '<remarks/>
        Public cod_area As String
        
        '<remarks/>
        Public cod_familia As String
        
        '<remarks/>
        Public cod_subfamilia As String
        
        '<remarks/>
        Public cod_producto As String
        
        '<remarks/>
        Public gls_producto As String
        
        '<remarks/>
        Public ind_stock As Boolean
        
        '<remarks/>
        Public ind_descontinuado As Boolean
        
        '<remarks/>
        Public gls_unidad_venta As String
        
        '<remarks/>
        Public fc_uemp_uvta As Integer
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class stValoresAtributos
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public msgError As String
        
        '<remarks/>
        Public cod_area As String
        
        '<remarks/>
        Public cod_familia As String
        
        '<remarks/>
        Public cod_subfamilia As String
        
        '<remarks/>
        Public cod_atributo As String
        
        '<remarks/>
        Public cod_valor_atributo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class stAtribXProd
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public msgError As String
        
        '<remarks/>
        Public cod_producto As String
        
        '<remarks/>
        Public cod_atributo As String
        
        '<remarks/>
        Public cod_valor_atributo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class stAtributos
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public msgError As String
        
        '<remarks/>
        Public cod_area As String
        
        '<remarks/>
        Public cod_familia As String
        
        '<remarks/>
        Public cod_subfamilia As String
        
        '<remarks/>
        Public cod_atributo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class stSubFamilias
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public msgError As String
        
        '<remarks/>
        Public cod_area As String
        
        '<remarks/>
        Public cod_familia As String
        
        '<remarks/>
        Public cod_subfamilia As String
        
        '<remarks/>
        Public gls_subfamilia As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/ecatSrv/Service1")>  _
    Public Class stFamilias
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public msgError As String
        
        '<remarks/>
        Public cod_area As String
        
        '<remarks/>
        Public cod_familia As String
        
        '<remarks/>
        Public gls_familia As String
    End Class
End Namespace
