'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2494
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2494.
'
Namespace cl.gms.andes.ws.catastroMaquinas
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="catastroMaquinasSrvSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class catastroMaquinasSrv
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("app.cl.gms.andes.ws.catastroMaquinas.catastroMaquinasSrv")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://pruebas.ws.andes.gms.cl/catastroMaquinasSrv.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dummy1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dummy1() As stRegistroMaquina
            Dim results() As Object = Me.Invoke("dummy1", New Object(-1) {})
            Return CType(results(0),stRegistroMaquina)
        End Function
        
        '<remarks/>
        Public Function Begindummy1(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dummy1", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Enddummy1(ByVal asyncResult As System.IAsyncResult) As stRegistroMaquina
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),stRegistroMaquina)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneRegistroMaquinasClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneRegistroMaquinasClientes(ByVal codigoSociedad As String, ByVal codigoCliente As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneRegistroMaquinasClientes", New Object() {codigoSociedad, codigoCliente, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneRegistroMaquinasClientes(ByVal codigoSociedad As String, ByVal codigoCliente As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneRegistroMaquinasClientes", New Object() {codigoSociedad, codigoCliente, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneRegistroMaquinasClientes(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneMaquinas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneMaquinas(ByVal codigoSociedad As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneMaquinas", New Object() {codigoSociedad, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneMaquinas(ByVal codigoSociedad As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneMaquinas", New Object() {codigoSociedad, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneMaquinas(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneTamanhoMaquinas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneTamanhoMaquinas(ByVal codigoSociedad As String, ByVal idMaquina As Integer, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneTamanhoMaquinas", New Object() {codigoSociedad, idMaquina, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneTamanhoMaquinas(ByVal codigoSociedad As String, ByVal idMaquina As Integer, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneTamanhoMaquinas", New Object() {codigoSociedad, idMaquina, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneTamanhoMaquinas(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneTamanhosPlanchas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneTamanhosPlanchas(ByVal codigoSociedad As String, ByVal codigoMaquina As Integer, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneTamanhosPlanchas", New Object() {codigoSociedad, codigoMaquina, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneTamanhosPlanchas(ByVal codigoSociedad As String, ByVal codigoMaquina As Integer, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneTamanhosPlanchas", New Object() {codigoSociedad, codigoMaquina, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneTamanhosPlanchas(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneTamanhosMantillas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneTamanhosMantillas(ByVal codigoSociedad As String, ByVal codigoMaquina As Integer, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneTamanhosMantillas", New Object() {codigoSociedad, codigoMaquina, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneTamanhosMantillas(ByVal codigoSociedad As String, ByVal codigoMaquina As Integer, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneTamanhosMantillas", New Object() {codigoSociedad, codigoMaquina, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneTamanhosMantillas(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresaNuevoRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ingresaNuevoRegistroMaquinaCliente(ByVal registro As stRegistroMaquina, ByRef msgError As String) As Integer
            Dim results() As Object = Me.Invoke("ingresaNuevoRegistroMaquinaCliente", New Object() {registro, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginingresaNuevoRegistroMaquinaCliente(ByVal registro As stRegistroMaquina, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ingresaNuevoRegistroMaquinaCliente", New Object() {registro, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndingresaNuevoRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizaRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function actualizaRegistroMaquinaCliente(ByVal registro As stRegistroMaquina, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.Invoke("actualizaRegistroMaquinaCliente", New Object() {registro, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginactualizaRegistroMaquinaCliente(ByVal registro As stRegistroMaquina, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("actualizaRegistroMaquinaCliente", New Object() {registro, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndactualizaRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminaRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function eliminaRegistroMaquinaCliente(ByVal idRegistro As Integer, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.Invoke("eliminaRegistroMaquinaCliente", New Object() {idRegistro, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BegineliminaRegistroMaquinaCliente(ByVal idRegistro As Integer, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("eliminaRegistroMaquinaCliente", New Object() {idRegistro, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndeliminaRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneRegistroMaquinaCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneRegistroMaquinaCliente(ByVal idRegistro As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneRegistroMaquinaCliente", New Object() {idRegistro, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneRegistroMaquinaCliente(ByVal idRegistro As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneRegistroMaquinaCliente", New Object() {idRegistro, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneRegistroMaquinaCliente(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneMaquinasPorCartera", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneMaquinasPorCartera(ByVal codigoSociedad As String, ByVal codEjecutivo As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneMaquinasPorCartera", New Object() {codigoSociedad, codEjecutivo, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneMaquinasPorCartera(ByVal codigoSociedad As String, ByVal codEjecutivo As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneMaquinasPorCartera", New Object() {codigoSociedad, codEjecutivo, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneMaquinasPorCartera(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtieneClientesPorMaquina", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneClientesPorMaquina(ByVal codigoSociedad As String, ByVal idMaquina As String, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("obtieneClientesPorMaquina", New Object() {codigoSociedad, idMaquina, msgError})
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneClientesPorMaquina(ByVal codigoSociedad As String, ByVal idMaquina As String, ByVal msgError As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneClientesPorMaquina", New Object() {codigoSociedad, idMaquina, msgError}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneClientesPorMaquina(ByVal asyncResult As System.IAsyncResult, ByRef msgError As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgError = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class stRegistroMaquina
        
        '<remarks/>
        Public idRegistro As Integer
        
        '<remarks/>
        Public codigoSociedad As String
        
        '<remarks/>
        Public codigoCliente As String
        
        '<remarks/>
        Public nombreCliente As String
        
        '<remarks/>
        Public idMaquina As Integer
        
        '<remarks/>
        Public dmcMaquina As String
        
        '<remarks/>
        Public idTamanhoMaquina As Integer
        
        '<remarks/>
        Public dmcTamanhoMaquina As String
        
        '<remarks/>
        Public cantidadMaquinas As Integer
        
        '<remarks/>
        Public numCuerposImpresores As String
        
        '<remarks/>
        Public conTorreBarniz As Boolean
        
        '<remarks/>
        Public idTamanhoPlancha As String
        
        '<remarks/>
        Public dmcTamanhoPlancha As String
        
        '<remarks/>
        Public idTamanhoMantilla As String
        
        '<remarks/>
        Public dmcTamanhoMantilla As String
        
        '<remarks/>
        Public observaciones As String
        
        '<remarks/>
        Public consumoPapel As Double
        
        '<remarks/>
        Public consumoPlanchas As Double
        
        '<remarks/>
        Public consumoTintasProceso As Double
        
        '<remarks/>
        Public consumoTintasPantone As Double
        
        '<remarks/>
        Public consumoBarniz As Double
        
        '<remarks/>
        Public consumoMantillas As Double
        
        '<remarks/>
        Public fechaRegistro As Date
        
        '<remarks/>
        Public fechaModificacion As Date
    End Class
End Namespace
